version: "3.6"
services:
  api:
    build:
      context: api
      target: "dev"
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - "./api:/app"
    env_file:
      - '.env.example'
  db:
    image: 'postgis/postgis:14-3.2-alpine'
    ports:
      - "${DB_PORT}:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - "${HOME}/docker/volumes/postgres:/var/lib/postgresql/data/"
  dev:
    build:
      context: app
      target: "dev"
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - "/app/node_modules"
      - "./app:/app"
  prod:
    image: "john-ruita/shpdb"
    build:
      context: app
      target: 'prod'
    ports:
      - "80:80"
